[package]
name = "blog_os"
version = "0.1.0"
authors = ["Tejaswi"]
edition = "2018"

[dependencies]
bootloader = "0.9"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
spin = "0.5.2"
volatile = "0.2.6"
